spring.application.name=Knowledge-hub
spring.datasource.url= jdbc:mysql://localhost:3306/knowledgeHub
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.security.user.name= nehal
#spring.security.user.password= nehal@123
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
logging.level.org.springframework.security=DEBUG
